name: GitHub CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 5 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: IssueSummary
      id: issueSummary
      uses: ./.github/actions/summaryAction
    - name: TemplateEngineAction
      id: templateEngineAction
      uses: ./
      with:
        repoName : ProtocolRedefined/Ecosystem-Template-Repository
        branchName : mesav/demoAction
        data: ${{ steps.issueSummary.outputs.openIssueSummary }}
        templateType: HandleBars
        sourceType: IssueReport
        ClientType: Teams
    - name: PrintOutput
      run: echo "${{ github.event }}"
